// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoAppAPI.DataBase;

#nullable disable

namespace ToDoAppAPI.database.migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230303222316_seeedo")]
    partial class seeedo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoAppAPI.Model.ListModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "shopping A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "To Do A"
                        },
                        new
                        {
                            Id = 3,
                            Name = "shopping B"
                        },
                        new
                        {
                            Id = 4,
                            Name = "To Do B"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Shardo"
                        });
                });

            modelBuilder.Entity("ToDoAppAPI.Model.PriorityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("priorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#ffffff",
                            Name = "P1",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#ffffff",
                            Name = "P2",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "#ffffff",
                            Name = "P3",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = "#ffffff",
                            Name = "P4",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "#ffffff",
                            Name = "P5",
                            Order = 5
                        });
                });

            modelBuilder.Entity("ToDoAppAPI.Model.StepModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("ToDoAppAPI.Model.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int?>("ListId")
                        .HasColumnType("int");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserCreatedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("UserCreatedId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 3, 4, 0, 23, 16, 253, DateTimeKind.Local).AddTicks(2136),
                            IsComplete = false,
                            ListId = 1,
                            PriorityId = 1,
                            Title = "bay 2 pins",
                            UserCreatedId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 3, 4, 0, 23, 16, 253, DateTimeKind.Local).AddTicks(2147),
                            IsComplete = false,
                            ListId = 1,
                            PriorityId = 1,
                            Title = "sell 2 pins hhh",
                            UserCreatedId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 3, 4, 0, 23, 16, 253, DateTimeKind.Local).AddTicks(2149),
                            IsComplete = false,
                            ListId = 2,
                            PriorityId = 1,
                            Title = "make coffe",
                            UserCreatedId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 3, 4, 0, 23, 16, 253, DateTimeKind.Local).AddTicks(2150),
                            IsComplete = false,
                            ListId = 2,
                            PriorityId = 1,
                            Title = "finish the vloge",
                            UserCreatedId = 1
                        });
                });

            modelBuilder.Entity("ToDoAppAPI.Model.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Tomas",
                            LastName = "Edison",
                            Password = "default",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Albert",
                            LastName = "Maki",
                            Password = "default",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("ToDoAppAPI.Models.UserListAccessModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevel = 0,
                            ListId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccessLevel = 0,
                            ListId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccessLevel = 0,
                            ListId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            AccessLevel = 0,
                            ListId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            AccessLevel = 0,
                            ListId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            AccessLevel = 0,
                            ListId = 5,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ToDoAppAPI.Model.StepModel", b =>
                {
                    b.HasOne("ToDoAppAPI.Model.TaskModel", "Task")
                        .WithMany("Steps")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ToDoAppAPI.Model.TaskModel", b =>
                {
                    b.HasOne("ToDoAppAPI.Model.ListModel", "List")
                        .WithMany("Tasks")
                        .HasForeignKey("ListId");

                    b.HasOne("ToDoAppAPI.Model.PriorityModel", "Priority")
                        .WithMany("Tasks")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDoAppAPI.Model.UserModel", "UserCreated")
                        .WithMany("Tasks")
                        .HasForeignKey("UserCreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("Priority");

                    b.Navigation("UserCreated");
                });

            modelBuilder.Entity("ToDoAppAPI.Models.UserListAccessModel", b =>
                {
                    b.HasOne("ToDoAppAPI.Model.ListModel", "List")
                        .WithMany("UserListAccess")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDoAppAPI.Model.UserModel", "User")
                        .WithMany("UserListAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDoAppAPI.Model.ListModel", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("UserListAccess");
                });

            modelBuilder.Entity("ToDoAppAPI.Model.PriorityModel", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ToDoAppAPI.Model.TaskModel", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ToDoAppAPI.Model.UserModel", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("UserListAccess");
                });
#pragma warning restore 612, 618
        }
    }
}
